// export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
// export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

exports.COUNTER_INCREMENT = 'COUNTER_INCREMENT';
exports.COUNTER_DECREMENT = 'COUNTER_DECREMENT';
exports.TODO_CHANGE = 'TODO_CHANGE';